# Generated by Django 3.2.8 on 2022-08-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devtime_chair', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='developer',
            new_name='name',
        ),
    ]
